# Starts all the services used by pyaleph, minus pyaleph itself. This is used for local development.
# Use the docker-compose/docker-compose.yml file for deployment.

version: '2.2'

services:
  mongodb:
    restart: always
    image: mongo:4.4
    command: mongod --storageEngine wiredTiger
    ports:
      - "27017:27017"
